#!/bin/sh
# A script to enable laptop power saving features for #! & Debian GNU+linux.
# http://crunchbanglinux.org/forums/topic/11954

# List of modules to unload, space seperated. Edit depending on your hardware and preferences.
modlist="uvcvideo"
# Bus list for runtime pm. Probably shouldn't touch this.
buslist="pci i2c"

case "$1" in
    true)
    # Enable some power saving settings while on battery

        echo 5 > /proc/sys/vm/laptop_mode

        echo 1500 > /proc/sys/vm/dirty_writeback_centisecs

       #echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
        echo 1 > /sys/module/snd_hda_intel/parameters/power_save

        echo 5 > /sys/class/backlight/acpi_video0/brightness

        for i in /sys/bus/usb/devices/*/power/autosuspend; do
            echo 1 > $i
        done

        for i in /sys/class/scsi_host/host*/link_power_management_policy; do
            echo min_power > $i
        done

        for mod in $modlist; do
            grep $mod /proc/modules >/dev/null || continue
            modprobe -r $mod 2>/dev/null
        done

        for bus in $buslist; do
            for i in /sys/bus/$bus/devices/*/power/control; do
                echo auto > $i
            done
        done
	hdparm -B 196 /dev/sda &> /dev/null
	echo '0' > '/proc/sys/kernel/nmi_watchdog'
	iw dev wlan0 set power_save on &> /dev/null
    ;;
    false)
       #Return settings to default on AC power
        echo 0 > /proc/sys/vm/laptop_mode
        echo 500 > /proc/sys/vm/dirty_writeback_centisecs
       # echo N > /sys/module/snd_hda_intel/parameters/power_save_controller
        echo 0 > /sys/module/snd_hda_intel/parameters/power_save
        echo 10 > /sys/class/backlight/acpi_video0/brightness
        for i in /sys/bus/usb/devices/*/power/autosuspend; do
            echo 2 > $i
        done
        for i in /sys/class/scsi_host/host*/link_power_management_policy
            do echo max_performance > $i
        done
        for mod in $modlist; do
            if ! lsmod | grep $mod; then
                modprobe $mod 2>/dev/null
            fi
        done
        for bus in $buslist; do
            for i in /sys/bus/$bus/devices/*/power/control; do
                echo on > $i
            done
        done
	hdparm -B 254 /dev/sda
	echo '1' > '/proc/sys/kernel/nmi_watchdog'
	iw dev wlan0 set power_save off &> /dev/null
    ;;
esac

exit 0
