#!/bin/sh

alias prompt_normal='PS1=$PS0'
alias prompt_alarm='PS1="$PS0\a"'
# alias prompt_status='PS1="$PS8"'

# alias aero2='sudo usb_modeswitch -v 12d1 -p 1446 -V 12d1 -P 1436 -J'
# alias aero2="sudo /usr/lib/udev/usb_modeswitch '/2-1.2'"
alias ath_reload="sudo rmmod ath10k_pci ; sudo rmmod ath10k_core ; sudo rmmod ath; sudo modprobe ath10k_pci"
# alias bboff="sudo rmmod nvidia; sudo tee /proc/acpi/bbswitch <<<OFF"
alias cal="cal -m3"
alias df="df -hT"
alias dfl="df -hTl --exclude-type=tmpfs --exclude-type=devtmpfs"
alias diffc="colordiff"
alias du="du -h"
alias e="emacs"
alias ebv="ebook-viewer"
#alias fbr="FBReader"
alias ffmpeg="ffmpeg -hide_banner"
alias free="free -h"
alias g="grep --color=auto"
alias gclean="git clean -d -x -f"
alias grep="grep --color=auto"
# alias gtick="aoss gtick"
alias h="history"
alias info="info --vi-keys"
alias j="jobs -l"
alias kdesrc-build='PATH="/usr/lib/ccache/bin/:$PATH" kdesrc-build'
alias ll="ls -hl --color=auto --group-directories-first"
alias lla="ls -hlA --color=auto --group-directories-first"
alias ls="ls -h --color=auto --group-directories-first"
alias lsps="sudo lsof +aL1 / | grep -v \" /var/tmp\""
alias lssuid='ls -hl /bin/| grep -P "^.*s.* \d root"'
alias m="mpv"
alias mount="mount | column -t"
alias mountl="mount | grep /dev/sd | column -t"
# alias mpdd="mpd ~/.config/mpd/mpd.conf"
# alias ncmpcpp="ncmpcpp --config ~/.config/ncmpcpp/config"
alias nc="ncat"
alias netcat="ncat"
alias paclog="less /var/log/pacman.log"
alias pacolog="pacolog -l 5"
alias pacsize='expac -H M "%011m\t%-20n\t%10d" $(comm -23 <(pacman -Qqen | sort) <(pacman -Qqg base base-devel | sort)) | sort -n'
alias psc='ps xawf -eo pid,user,cgroup,args'
alias rm="rm -I"
alias rmwine="rm -rf ~/.local/share/applications/wine* ~/.wine ~/.local/share/desktop-directories/wine* ~/.config/menus/applications-merged/wine*"
alias se="sudoedit"
# alias td="\$EDITOR ~/doc/notes/todo"
alias tree="tree -AC"
alias sysupd="grep -v ^# /etc/pacman.d/ignored | cut -d'=' -f 2- | tr ' ' '\n'| yay -S --needed --noconfirm -"
alias units="units -H ~/.cache/units_history"
alias usbspeed="lsusb -t"
alias v="nvim"
alias vim="nvim"
alias whatstesting="pacman -Sl testing community-testing multilib-testing --color always | less"
alias whatstestingi="pacman -Sl testing community-testing multilib-testing --color always | less | grep installed: | less"
alias xrnat="xrandr -s 0"
alias xmonitor_on="xrandr --output HDMI-1 --auto --right-of eDP-1"
alias xmonitor_off="xrandr --output HDMI-1 --off"
alias y="yay"
alias yaourt="yay"

