#!/bin/bash

pacver() {
    pacman -Qi "$1" | grep "Version"
}

pacdes() {
    pacman -Qi "$1" | grep "Description"
}

lsusers() {
    awk -F'[/:]' '{if ($3 >= 1000 && $3 != 65534) print $1}' /etc/passwd
}

manswitch() {
    man "$1" | less -p "^ +$2";
}

whereis2() {
    whereis "$1" | cut -d: -f2
}

sysupd_testing() {
    # don't put any 8s or 1s in the path
    repo=/etc/pacman.d/repo-active
    for r in "$repo"/8*; do
        sudo mv -v "$r" "$(echo "$r"| sed 's/8/1/')"
    done
    grep -v '^#' /etc/pacman.d/ignored | cut -d'=' -f 2- | tr ' ' '\n'| yay -S --needed --noconfirm -
    for r in "$repo"/1*; do
        sudo mv -v "$r" "$(echo "$r"| sed 's/1/8/')"
    done
}

yay-testing() {
    repo=/etc/pacman.d/repo-active
    for r in "$repo"/8*; do
        sudo mv -v "$r" "$(echo "$r"| sed 's/8/1/')"
    done
    yay "$@"
    for r in "$repo"/1*; do
        sudo mv -v "$r" "$(echo "$r"| sed 's/1/8/')"
    done
}
#. .functions
#
#extract() {
#	local c e i
#
#	(($#)) || return
#
#	for i; do
#		c=''
#		e=1
#
#		if [[ ! -r $i ]]; then
#			echo "$0: file is unreadable: \`$i'" >&2
#			continue
#		fi
#
#		case $i in *.t@(gz|lz|xz|b@(2|z?(2))|a@(z|r?(.@(Z|bz?(2)|gz|lzma|xz)))))
#			c='bsdtar xvf';;
#		*.7z)
#			c='7z x';;
#		*.Z)
#			c='uncompress';;
#		*.bz2)
#			c='bunzip2';;
#		*.exe)
#			c='cabextract';;
#		*.gz)
#			c='gunzip';;
#		*.rar)
#			c='unrar x';;
#		*.xz)
#			c='unxz';;
#		*.zip)
#			c='unzip';;
#		*)
#			echo "$0: unrecognized file extension: \`$i'" >&2
#			continue;;
#		esac
#	command $c "$i" e=$?
#done
#
#return $e 
#}
# configure xdg-open
# Enhance colored ls output
#eval $(dircolors -b)
#
## x - archive extractor
## usage: x <file>
#x ()
#{
#  if [ -f $1 ] ; then
#    case $1 in
#      *.tar.bz2)   tar xjf $1   ;;
#      *.tar.gz)    tar xzf $1   ;;
#      *.bz2)       bunzip2 $1   ;;
#      *.rar)       rar x $1     ;;
#      *.gz)        gunzip $1    ;;
#      *.tar)       tar xf $1    ;;
#      *.tbz2)      tar xjf $1   ;;
#      *.tgz)       tar xzf $1   ;;
#      *.zip)       unzip $1     ;;
#      *.Z)         uncompress $1;;
#      *.7z)        7z x $1      ;;
#      *.xz)        unxz $1      ;;
#      *)           echo "'$1' cannot be extracted via ex()" ;;
#    esac
#  else
#    echo "'$1' is not a valid file"
#  fi
#}
